### ISSUE TITLE
Can you provide me with the markdown component?

### ISSUE THREAD

**Issue by Meowv** [StardustDL/acblog#18]
Can you provide me with the markdown component?

`AcBlog.UI.Components.Markdown`

Thanks

**Comment by StardustDL** [comment]
Thank you for your attention.

I have no plan for its releases for now since I only use this custom Markdown component to develop AcBlog and its API might be changed in future. But if you still need it, I'm glad to create a preview package to make it easy to use.

Do you need an independent package for `AcBlog.UI.Components.Markdown`?

**Comment by Meowv** [comment]
Yes, I need this package, thank you very much.

I am using Blazor to develop a blog system that requires markdown components, so I want to refer to it.

**Comment by StardustDL** [comment]
I have moved it to a new repository for the individual Markdown component, since the one of AcBlog depends on other components.

The new repository is [StardustDL/RazorComponents.Markdown](https://github.com/StardustDL/RazorComponents.Markdown). You can go there for more information.

Since I just migrated for two hour, maybe something is not fully tested (for the demo in that repo, it works). If you find any bugs about this component, please create issues in the new repository, thanks.
